# tmuxinator config for running distributed consensus simulation
# Save as .tmuxinator.yml and run with: tmuxinator start -p .tmuxinator.yml
name: gnn
root: /home/marko/PROJECTS/distributed_computation/simple_gnn
pre_window: source ~/PROJECTS/graphs_venv/bin/activate
windows:
  - nodes:
      layout: even-horizontal
      synchronize: after
      panes:
        - |
          <%- if args[0] == "mixed" or args[0] == "remote" %>
          ssh -t pi@rpi0.local '/home/pi/distributed_computation/simple_gnn/docker/start_docker.sh monika_cont'
          <%- end %>
          python3 node.py 0
        - |
          <%- if args[0] == "remote" %>
          ssh -t pi@rpi1.local '/home/pi/distributed_computation/simple_gnn/docker/start_docker.sh monika_cont'
          <%- end %>
          python3 node.py 1
        - |
          <%- if args[0] == "remote" %>
          ssh -t pi@rpi2.local '/home/pi/distributed_computation/simple_gnn/docker/start_docker.sh monika_cont'
          <%- end %>
          python3 node.py 2
        - |
          <%- if args[0] == "remote" %>
          ssh -t pi@rpi3.local '/home/pi/distributed_computation/simple_gnn/docker/start_docker.sh monika_cont'
          <%- end %>
          python3 node.py 3
        - |
          <%- if args[0] == "remote" %>
          ssh -t pi@rpi4.local '/home/pi/distributed_computation/simple_gnn/docker/start_docker.sh monika_cont'
          <%- end %>
          python3 node.py 4
  - central:
      panes:
        - |
          history -s "python3 central.py <%= @args[0] %>.yaml"
