nodes:
  node0: [127.0.0.1, 5000]
  node1: [127.0.0.1, 5001]
  node2: [127.0.0.1, 5002]
  node3: [127.0.0.1, 5003]
  node4: [127.0.0.1, 5004]

model:
  pathOld: "config/model.pth"
  path: "config/best_model_2.pt" # "config/model.pth"

test_data:
  # path: "config/test_dataset.pth"
  path: "Dataset/criticality_dataset_nc1.pt"
  pathOld: "config/test_dataset.pth"
  index: 8
  indexOld: 0